# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Leonard Gies\Desktop\Python\Texting-App\Texting-App-Client\src\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sendButton = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.chatBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chatBrowser.setFont(font)
        self.chatBrowser.setObjectName("chatBrowser")
        self.gridLayout.addWidget(self.chatBrowser, 0, 0, 1, 2)
        self.sendInput = QtWidgets.QTextEdit(self.centralWidget)
        self.sendInput.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sendInput.setFont(font)
        self.sendInput.setObjectName("sendInput")
        self.gridLayout.addWidget(self.sendInput, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Texting App"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.sendInput.setPlaceholderText(_translate("MainWindow", "Type Text Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
